export const IMAGENET_CLASSES = {
  0: 'bare',
  1: 'calculator',
  2: 'camera',
  3: 'chat',
  4: 'editor',
  5: 'form',
  6: 'gallery',
  7: 'list',
  8: 'login',
  9: 'maps',
  10: 'mediaplayer',
  11: 'menu',
  12: 'modal',
  13: 'news',
  14: 'other',
  15: 'profile',
  16: 'search',
  17: 'settings',
  18: 'terms',
  19: 'tutorial',
}